### ISSUE TITLE
spark + nstore-session db name

### ISSUE THREAD

**Issue by mhussa** [creationix/nstore-session#1]
nstore-session as it is works correctly in a single server process setup but it might be worth adding a caveat to the readme about what will work in a multiprocess environment like spark.  Mounting apps using the same db name will go wrong.

The dbname can be prefixed with process.pid to prevent clashes but the side effect is all sessions are cleared on restart.

**Comment by mhussa** [comment]
Something just dawned on me, The memory session store would have a different problem in that the client request may go to a different mounted app and then a new session would be created.  Multiple session records for the same client in different mounted app processes.

If the spark process handled the sessions then it would work but from what I can see of the spark code there's no connect dependancy.

What were your intentions in this regard, will spark handle sessions?

**Comment by creationix** [comment]
My intent is to require the user to use a network aware session store when in multi-process mode.  It's pretty trivial to write a wrapper around nStore to make it network aware.  Or using something like Redis, CouchDB, or a plain in-memory node server would be simple.

As far as nStore I plan on locking the db file so it doesn't corrupt itself when two processes try to access the same db.

**Comment by mhussa** [comment]
OK fair enough, thats sensible.  Thanks.
